version: 2.1

executors:
  golang:
    working_directory: /go/src/moul.io/funcenter
    docker:
      - image: circleci/golang:1.16
    environment:
      GO111MODULE: "on"

orbs:
  codecov: codecov/codecov@1.1.3
  moul: moul/build@1.16.0
  retry: moul/retry@0.6.0
  #dl: moul/dl@1.7.0
  tools: gotest/tools@0.0.13

jobs:
  go-build:
    executor: golang
    steps:
      - checkout
      - retry/install
      - tools/mod-download
      - tools/mod-tidy-check
      - run: retry -m 3 make install
      - run: retry -m 3 make test
      - moul/install_golangci-lint
      - run: PATH=$PATH:$(pwd)/bin retry -m 3 make lint
      - codecov/upload:
          file: coverage.txt

workflows:
  main:
    jobs:
      - go-build
